"""
Graph Structure Builder for Fraud Detection GNN

SINGLE SOURCE OF TRUTH for graph schema.

This module builds the heterogeneous graph structure from node/edge parquet artifacts.
Feature engineering is handled separately in src.features.gnn.node_features.

Architecture (Clean Separation):
  • Structure: This module (data layer)
  • Features: src.features.gnn.node_features (feature layer)
  • Clean separation of concerns

Graph Structure:
  • 6 Node Types: user, listing, ip, email, phone, address
  • 8 Forward Edge Types + 8 Reverse (auto-generated by ToUndirected)
  • Temporal filtering support for training

Entity Naming Convention:
  • External name: listing_id (logs, configs, docs)
  • Internal storage: insertion_id (database object_reference)
  • Graph indexing: 0..N-1 (CRITICAL for embeddings)

Usage:
    from src.data.graph.graph_structure import build_graph, get_graph_metadata
    
    # Build full graph
    graph = build_graph()
    
    # Build temporal graph (for training splits)
    graph = build_graph(cutoff_date=datetime(2024, 1, 1))
    
    # Get metadata (fast - uses cached .pkl)
    metadata = get_graph_metadata()
"""

import logging
import pickle
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple, List

import polars as pl
import torch
import torch_geometric.transforms as T
from torch_geometric.data import HeteroData

from src.features.gnn.node_features import create_all_node_features
from src.utils.hydra_utils import resolve_path

logger = logging.getLogger(__name__)

# Type alias for graph metadata
GraphMetadata = Tuple[List[str], List[Tuple[str, str, str]]]

# Artifact paths
ARTIFACTS_DIR = resolve_path("artifacts")
GRAPH_PT = resolve_path("artifacts/graph.pt")
MAPPINGS_PKL = resolve_path("artifacts/mappings.pkl")

# Node parquet files
NODES_USER = resolve_path("artifacts/nodes_user.parquet")
NODES_LISTING = resolve_path("artifacts/nodes_listing.parquet")
NODES_IP = resolve_path("artifacts/nodes_ip.parquet")
NODES_EMAIL = resolve_path("artifacts/nodes_email.parquet")
NODES_PHONE = resolve_path("artifacts/nodes_phone.parquet")
NODES_ADDRESS = resolve_path("artifacts/nodes_address.parquet")

# Edge parquet files
EDGES_USER_POSTS = resolve_path("artifacts/edges_user_posts_listing.parquet")


def load_node_mapping(df: pl.DataFrame, id_col: str, node_type: str) -> tuple[dict, pl.DataFrame]:
    """
    Create mapping from Raw ID -> PyG Index (0..N-1).
    
    Args:
        df: Node DataFrame
        id_col: Column name containing node IDs
        node_type: Node type name (for logging)
        
    Returns:
        Tuple of (mapping dict, deduplicated DataFrame)
    """
    logger.info(f"Processing {node_type} nodes...")
    
    # Ensure unique nodes
    df = df.unique(subset=[id_col])
    
    # Create mapping: raw_id -> sequential index
    ids = df[id_col].to_list()
    mapping = {raw_id: i for i, raw_id in enumerate(ids)}
    
    return mapping, df


def build_graph(cutoff_date: Optional[datetime] = None) -> HeteroData:
    """
    Build heterogeneous graph from parquet artifacts.
    
    This is a forward-refactored version that separates structure from features.
    Feature engineering is delegated to src.features.gnn.node_features.
    
    Args:
        cutoff_date: Optional temporal cutoff for training splits.
                     Only includes listings/edges before this date to prevent leakage.
    
    Returns:
        HeteroData graph with:
        - Node features (from graph_node_features)
        - Edge structure
        - Timestamps for temporal splits
        - Reverse edges (auto-generated by ToUndirected)
    
    Example:
        >>> # Full graph for initial save
        >>> graph = build_graph()
        
        >>> # Temporal graph for training window
        >>> graph = build_graph(cutoff_date=datetime(2024, 1, 1))
    """
    logger.info("=" * 70)
    logger.info("BUILDING GRAPH")
    logger.info("=" * 70)
    
    if cutoff_date is not None:
        logger.info(f"Temporal filtering: cutoff_date={cutoff_date}")
    
    # ========================================================================
    # STEP 1: Load Node Parquets
    # ========================================================================
    logger.info("Loading node parquets...")
    df_user = pl.read_parquet(NODES_USER)
    df_listing = pl.read_parquet(NODES_LISTING)
    df_ip = pl.read_parquet(NODES_IP)
    df_email = pl.read_parquet(NODES_EMAIL)
    df_phone = pl.read_parquet(NODES_PHONE)
    df_address = pl.read_parquet(NODES_ADDRESS)
    
    # ========================================================================
    # STEP 2: Apply Temporal Filtering (if cutoff_date provided)
    # ========================================================================
    if cutoff_date is not None:
        df_listing = df_listing.with_columns(
            pl.col("submission_at").cast(pl.Datetime("ns"))
        )
        df_listing = df_listing.filter(pl.col("submission_at") < cutoff_date)
        logger.info(f"Filtered listings: {len(df_listing)} before cutoff")
    
    # ========================================================================
    # STEP 3: Create Node Mappings (ID -> Index)
    # ========================================================================
    logger.info("Creating node mappings...")
    user_map, df_user = load_node_mapping(df_user, "user_id", "user")
    listing_map, df_listing = load_node_mapping(df_listing, "insertion_id", "listing")
    ip_map, df_ip = load_node_mapping(df_ip, "user_ip_address", "ip")
    email_map, df_email = load_node_mapping(df_email, "email", "email")
    phone_map, df_phone = load_node_mapping(df_phone, "phone", "phone")
    addr_map, df_address = load_node_mapping(df_address, "address_id", "address")
    
    # Store all mappings
    mappings = {
        "user": user_map,
        "listing": listing_map,
        "ip": ip_map,
        "email": email_map,
        "phone": phone_map,
        "address": addr_map
    }
    
    # ========================================================================
    # STEP 4: Create Node Features (delegated to feature layer)
    # ========================================================================
    logger.info("Creating node features (feature engineering layer)...")
    features = create_all_node_features(
        df_listing=df_listing,
        df_user=df_user,
        df_address=df_address,
        n_ip=len(ip_map),
        n_email=len(email_map),
        n_phone=len(phone_map)
    )
    
    # ========================================================================
    # STEP 5: Build HeteroData Graph
    # ========================================================================
    logger.info("Building HeteroData structure...")
    data = HeteroData()
    
    # Listing nodes (rich features + labels + timestamps)
    data['listing'].x = features['listing']['x']
    data['listing'].y = features['listing']['y']
    data['listing'].timestamp = features['listing']['timestamp']
    data['listing'].num_nodes = len(listing_map)
    
    # User nodes
    data['user'].x = features['user']['x']
    data['user'].num_nodes = len(user_map)
    
    # Address nodes (lat/lon features)
    data['address'].x = features['address']['x']
    data['address'].num_nodes = len(addr_map)
    
    # Entity nodes (IP, Email, Phone)
    data['ip'].x = features['ip']['x']
    data['ip'].num_nodes = len(ip_map)
    
    data['email'].x = features['email']['x']
    data['email'].num_nodes = len(email_map)
    
    data['phone'].x = features['phone']['x']
    data['phone'].num_nodes = len(phone_map)
    
    # ========================================================================
    # STEP 6: Process Edges
    # ========================================================================
    logger.info("Processing edges...")
    
    # Create timestamp mappings for edge temporal filtering
    listing_time_map = dict(
        zip(
            df_listing["insertion_id"],
            df_listing["submission_at"].cast(pl.Datetime("ns")).cast(pl.Int64)
        )
    )
    
    # Compute user's earliest listing time (for user-based edges)
    user_earliest_listing_map = {}
    if cutoff_date is not None:
        user_posts = pl.read_parquet(EDGES_USER_POSTS)
        user_posts = user_posts.join(
            df_listing.select(["insertion_id", "submission_at"]),
            left_on="target",
            right_on="insertion_id",
            how="inner"
        )
        user_earliest = (
            user_posts.group_by("source")
            .agg(pl.col("submission_at").min().alias("earliest_listing_time"))
            .with_columns(
                pl.col("earliest_listing_time").cast(pl.Datetime("ns")).cast(pl.Int64)
            )
        )
        user_earliest_listing_map = dict(
            zip(user_earliest["source"], user_earliest["earliest_listing_time"])
        )
    
    # Edge processing helper
    def add_edge(
        filename: str,
        src_col: str,
        dst_col: str,
        src_type: str,
        dst_type: str,
        rel_name: str,
        edge_type: str = "listing_to_target"
    ):
        """
        Add edge to graph with temporal filtering.
        
        Args:
            filename: Edge parquet filename
            src_col: Source ID column name
            dst_col: Target ID column name
            src_type: Source node type
            dst_type: Target node type
            rel_name: Edge relation name
            edge_type: Temporal filtering strategy:
                - "listing_to_target": source is listing, filter by source
                - "target_to_listing": target is listing, filter by target
                - "user_based": edge involves user, filter by user's earliest listing
        """
        logger.info(f"  {src_type} -{rel_name}-> {dst_type}")
        edge_path = ARTIFACTS_DIR / filename
        
        if not edge_path.exists():
            logger.warning(f"  ⚠️ {filename} not found. Skipping.")
            return
        
        df_edge = pl.read_parquet(edge_path)
        
        # Apply temporal filtering
        if cutoff_date is not None:
            if edge_type == "listing_to_target":
                # Filter by source (listing)
                df_edge = df_edge.join(
                    df_listing.select(["insertion_id"]),
                    left_on="source",
                    right_on="insertion_id",
                    how="inner"
                ).select(["source", "target"])
            elif edge_type == "target_to_listing":
                # Filter by target (listing)
                df_edge = df_edge.join(
                    df_listing.select(["insertion_id"]),
                    left_on="target",
                    right_on="insertion_id",
                    how="inner"
                ).select(["source", "target"])
            elif edge_type == "user_based":
                # Filter by user's earliest listing
                if user_earliest_listing_map:
                    df_edge = df_edge.join(
                        user_earliest.select(["source"]),
                        left_on="source",
                        right_on="source",
                        how="inner"
                    ).select(["source", "target"])
                else:
                    logger.info(f"  ⚠️ No users with listings before cutoff")
                    return
        
        if df_edge.is_empty():
            logger.info(f"  ⚠️ No edges after temporal filtering")
            return
        
        # Map IDs to indices
        src_map = mappings[src_type]
        dst_map = mappings[dst_type]
        
        src_indices = [src_map.get(id_) for id_ in df_edge[src_col].to_list()]
        dst_indices = [dst_map.get(id_) for id_ in df_edge[dst_col].to_list()]
        
        # Filter out None values (IDs not in mapping)
        valid_mask = [(s is not None and d is not None) for s, d in zip(src_indices, dst_indices)]
        src_indices = [s for s, v in zip(src_indices, valid_mask) if v]
        dst_indices = [d for d, v in zip(dst_indices, valid_mask) if v]
        
        if not src_indices:
            logger.info(f"  ⚠️ No valid edges after mapping")
            return
        
        # Create edge tensor
        edge_index = torch.tensor([src_indices, dst_indices], dtype=torch.long)
        data[src_type, rel_name, dst_type].edge_index = edge_index
        
        # Assign timestamps
        edge_times = []
        if edge_type == "listing_to_target":
            # Timestamp from source (listing)
            valid_src_ids = [id_ for id_, v in zip(df_edge[src_col].to_list(), valid_mask) if v]
            edge_times = [listing_time_map.get(id_, 0) for id_ in valid_src_ids]
        elif edge_type == "target_to_listing":
            # Timestamp from target (listing)
            valid_dst_ids = [id_ for id_, v in zip(df_edge[dst_col].to_list(), valid_mask) if v]
            edge_times = [listing_time_map.get(id_, 0) for id_ in valid_dst_ids]
        elif edge_type == "user_based" and cutoff_date is not None:
            # Timestamp from user's earliest listing
            valid_src_ids = [id_ for id_, v in zip(df_edge[src_col].to_list(), valid_mask) if v]
            edge_times = [user_earliest_listing_map.get(id_, 0) for id_ in valid_src_ids]
        
        if edge_times:
            data[src_type, rel_name, dst_type].timestamp = torch.tensor(edge_times, dtype=torch.long)
        
        logger.info(f"  ✓ Added {len(src_indices)} edges")
    
    # Add all edges (8 forward edge types)
    add_edge("edges_user_posts_listing.parquet", "source", "target", 
             "user", "listing", "posts", edge_type="target_to_listing")
    
    add_edge("edges_user_uses_ip.parquet", "source", "target",
             "user", "ip", "uses", edge_type="user_based")
    
    add_edge("edges_user_has_email.parquet", "source", "target",
             "user", "email", "has_email", edge_type="user_based")
    
    add_edge("edges_listing_contact_email.parquet", "source", "target",
             "listing", "email", "has_contact_email", edge_type="listing_to_target")
    
    add_edge("edges_listing_billing_email.parquet", "source", "target",
             "listing", "email", "has_billing_email", edge_type="listing_to_target")
    
    add_edge("edges_listing_phone.parquet", "source", "target",
             "listing", "phone", "has_phone", edge_type="listing_to_target")
    
    add_edge("edges_listing_located_at.parquet", "source", "target",
             "listing", "address", "located_at", edge_type="listing_to_target")
    
    add_edge("edges_listing_billing_addr.parquet", "source", "target",
             "listing", "address", "has_billing_addr", edge_type="listing_to_target")
    
    # ========================================================================
    # STEP 7: Apply ToUndirected Transform (creates reverse edges)
    # ========================================================================
    logger.info("Applying ToUndirected transform (creating reverse edges)...")
    transform = T.ToUndirected()
    data = transform(data)
    
    # Copy timestamps to reverse edges
    for edge_type in list(data.edge_types):
        if 'timestamp' in data[edge_type]:
            src_type, rel_name, dst_type = edge_type
            reverse_type = (dst_type, f"rev_{rel_name}", src_type)
            
            if reverse_type in data.edge_types and 'timestamp' not in data[reverse_type]:
                data[reverse_type].timestamp = data[edge_type].timestamp
    
    # ========================================================================
    # STEP 8: Save Graph (only if full graph, not temporal)
    # ========================================================================
    if cutoff_date is None:
        logger.info("Saving graph to artifacts/...")
        torch.save(data, GRAPH_PT)
        
        with open(MAPPINGS_PKL, "wb") as f:
            pickle.dump(mappings, f)
        
        # Cache metadata for fast loading
        metadata = data.metadata()
        metadata_path = str(GRAPH_PT).replace('.pt', '_metadata.pkl')
        with open(metadata_path, "wb") as f:
            pickle.dump(metadata, f)
        logger.info(f"  ✓ Cached metadata to {Path(metadata_path).name}")
    else:
        logger.info("Temporal graph built (not saved to disk)")
    
    # ========================================================================
    # Final Summary
    # ========================================================================
    logger.info("=" * 70)
    logger.info("GRAPH COMPLETE")
    logger.info("=" * 70)
    logger.info(f"Node types: {len(data.node_types)}")
    logger.info(f"Edge types: {len(data.edge_types)} (forward + reverse)")
    
    for node_type in data.node_types:
        logger.info(f"  {node_type}: {data[node_type].num_nodes} nodes")
    
    logger.info("=" * 70)
    
    return data


def get_graph_metadata(graph_path: str = "artifacts/graph.pt") -> GraphMetadata:
    """
    Get graph metadata efficiently.
    
    Loads cached metadata.pkl if available (~1ms), otherwise loads full graph (~2s).
    This avoids loading 200MB+ graphs just to get a tiny metadata tuple.
    
    Args:
        graph_path: Path to saved graph.pt file
    
    Returns:
        Tuple of (node_types, edge_types) where:
        - node_types: List[str] - node type names
        - edge_types: List[Tuple[str, str, str]] - (src, relation, dst) tuples
    
    Example:
        >>> metadata = get_graph_metadata()
        >>> node_types, edge_types = metadata
        >>> model = SAGEWrapper(metadata, ...)
    
    Note:
        The cached metadata.pkl is created automatically by build_graph().
        If not found, falls back to loading the full graph.
    """
    graph_path = resolve_path(graph_path)
    metadata_path = str(graph_path).replace('.pt', '_metadata.pkl')
    
    # Try cached metadata first (FAST)
    try:
        with open(metadata_path, 'rb') as f:
            metadata = pickle.load(f)
            logger.debug(f"Loaded cached metadata from {Path(metadata_path).name}")
            return metadata
    except FileNotFoundError:
        logger.warning(f"Cached metadata not found, loading full graph (slow)...")
    
    # Fallback: load full graph (SLOW)
    try:
        graph = torch.load(graph_path, weights_only=False)
        metadata = graph.metadata()
        
        # Cache for next time
        try:
            with open(metadata_path, 'wb') as f:
                pickle.dump(metadata, f)
            logger.info(f"Cached metadata to {Path(metadata_path).name}")
        except Exception as e:
            logger.warning(f"Could not cache metadata: {e}")
        
        return metadata
    except FileNotFoundError:
        raise FileNotFoundError(
            f"Graph not found at {graph_path}. "
            "Run 'python src/data/graph/create_artifacts.py' first."
        )


def validate_graph_metadata(metadata: GraphMetadata, strict: bool = True) -> dict:
    """
    Validate graph metadata completeness.
    
    Checks:
    1. All expected node types present (6 types)
    2. Forward/reverse edges balanced (ToUndirected should create equal counts)
    3. Minimum edge count (8 forward edges expected)
    
    Args:
        metadata: Tuple of (node_types, edge_types)
        strict: If True, raise ValueError on failure
    
    Returns:
        Dictionary with validation results:
        {
            'valid': bool,
            'errors': List[str],
            'warnings': List[str],
            'node_types': int,
            'edge_types': int,
            'forward_edges': int,
            'reverse_edges': int
        }
    
    Raises:
        ValueError: If strict=True and validation fails
    
    Example:
        >>> metadata = get_graph_metadata()
        >>> result = validate_graph_metadata(metadata, strict=False)
        >>> if not result['valid']:
        ...     print(f"Errors: {result['errors']}")
    """
    node_types, edge_types = metadata
    
    result = {
        "valid": True,
        "errors": [],
        "warnings": [],
        "node_types": len(node_types),
        "edge_types": len(edge_types),
        "forward_edges": 0,
        "reverse_edges": 0,
    }
    
    # Expected node types (our fraud detection schema)
    expected_nodes = {"listing", "user", "ip", "email", "phone", "address"}
    missing_nodes = expected_nodes - set(node_types)
    extra_nodes = set(node_types) - expected_nodes
    
    if missing_nodes:
        result["valid"] = False
        result["errors"].append(f"Missing node types: {missing_nodes}")
    
    if extra_nodes:
        result["warnings"].append(f"Extra node types: {extra_nodes}")
    
    # Count forward vs reverse edges
    for src, rel, dst in edge_types:
        if rel.startswith("rev_"):
            result["reverse_edges"] += 1
        else:
            result["forward_edges"] += 1
    
    # Check edge symmetry (ToUndirected should create equal counts)
    if result["forward_edges"] != result["reverse_edges"]:
        result["warnings"].append(
            f"Edge asymmetry: {result['forward_edges']} forward, "
            f"{result['reverse_edges']} reverse (expected equal after ToUndirected)"
        )
    
    # Minimum 8 forward edges expected (our schema)
    if result["forward_edges"] < 8:
        result["valid"] = False
        result["errors"].append(
            f"Expected at least 8 forward edges, got {result['forward_edges']}"
        )
    
    if strict and not result["valid"]:
        error_msg = "; ".join(result['errors'])
        raise ValueError(f"Metadata validation failed: {error_msg}")
    
    return result


if __name__ == "__main__":
    # CLI usage: python -m src.data.graph.graph_structure
    build_graph()
